# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Estados.create(name: "Distrito Federal")
Estados.create(name: "Aguascalientes")
Estados.create(name: "Baja California")
Estados.create(name: "Baja California Sur")
Estados.create(name: "Campeche")
Estados.create(name: "Chiapas")
Estados.create(name: "Chihuaha")
Estados.create(name: "Coahuila")
Estados.create(name: "Colima")
Estados.create(name: "Durango")
Estados.create(name: "Guanajuato")
Estados.create(name: "Guerrero")
Estados.create(name: "Hidalgo")
Estados.create(name: "Jalisco")
Estados.create(name: "México")
Estados.create(name: "Michoacán")
Estados.create(name: "Morelos")
Estados.create(name: "Nayarit")
Estados.create(name: "Nuevo León")
Estados.create(name: "Oaxaca")
Estados.create(name: "Puebla")
Estados.create(name: "Querétaro")
Estados.create(name: "Quintana Roo")
Estados.create(name: "San Luis Potosí")
Estados.create(name: "Sinaloa")
Estados.create(name: "Sonora")
Estados.create(name: "Tabasco")
Estados.create(name: "Tamaulipas")
Estados.create(name: "Tlaxcala")
Estados.create(name: "Veracruz")
Estados.create(name: "Yucatán")
Estados.create(name: "Zacatecas")